
cc_library(
    name = 'ecfs_common',
    srcs = [
    'codec.cpp',
    'configs.cpp',
    'md5lib.cpp',
    'thread_pool.cpp',
    'utils.cpp'
    ],
    deps = [
    '//thirdparty/glog:glog',
    '//thirdparty/boost:filesystem',
    '//thirdparty/boost:system',
    '//thirdparty/boost:thread',
    '//thirdparty/boost:date_time',
    '//thirdparty/fecpp:fecpp',
    ],
)

