/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "datanode_constants.h"



const datanodeConstants g_datanode_constants;

datanodeConstants::datanodeConstants() {
}



