/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef datanode_CONSTANTS_H
#define datanode_CONSTANTS_H

#include "datanode_types.h"



class datanodeConstants {
 public:
  datanodeConstants();

};

extern const datanodeConstants g_datanode_constants;



#endif
