/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef namenode_CONSTANTS_H
#define namenode_CONSTANTS_H

#include "namenode_types.h"



class namenodeConstants {
 public:
  namenodeConstants();

};

extern const namenodeConstants g_namenode_constants;



#endif
