/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "namenode_constants.h"



const namenodeConstants g_namenode_constants;

namenodeConstants::namenodeConstants() {
}



