/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef recovery_CONSTANTS_H
#define recovery_CONSTANTS_H

#include "recovery_types.h"



class recoveryConstants {
 public:
  recoveryConstants();

};

extern const recoveryConstants g_recovery_constants;



#endif
